name: Sinp Frontend CI/CD

# master 브랜치에 push, PR 이벤트 발생시 동작.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: Node.js 설치
      uses: actions/setup-node@v3
      with:
        node-version: '20' # 또는 원하는 Node.js 버전

    - name: 의존성 설치
      run: npm install

    - name: 빌드
      run: npm run build
    
    # Docker 이미지 Build (2)
    - name: docker image build
      run: docker build -t qlido/sinpf .
    
    # DockerHub Login (3)
    - name: docker login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Docker Hub push (4)
    - name: docker Hub push
      run: docker push qlido/sinpf

    - name: Connect to WAS & Execute Application
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.WAS_HOST }}
        username: ${{ secrets.WAS_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.WAS_SSH_PORT }}
        script: |
          cd /home/ubuntu/Something-Hilarious-Frontend
          docker-compose stop
          docker-compose pull
          docker-compose up -d